name: GitHub Actions - System Requirements
on:

####----------------------------------------------------------------------------

  workflow_dispatch:

    name: Manual Deployment
    description: 'Triggering Manual Deployment'

    inputs:

      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

      tags:
        description: 'System Requirements'

####----------------------------------------------------------------------------

  push:

    branches: [ master ]
    paths:
      - action.yaml

####----------------------------------------------------------------------------

env:

  ## Variables: ----------------------------------------------------------------

  ## AWS + Terraform CLI components
  AWSCLI_CLI:    ${{ vars.AWSCLI_CLI }}

  ## AWS CLI package attributes
  AWSCLI_DOWNLOAD: ${{ vars.AWSCLI_DOWNLOAD }}
  AWSCLI_PACKAGE:  ${{ vars.AWSCLI_PACKAGE }}

  ## Default/Custom toolset + Requirements
  CUSTOM_TOOLS:  ${{ vars.CUSTOM_TOOLS }}
  DEFAULT_TOOLS: ${{ vars.DEFAULT_TOOLS }}

  ## Python (Packages) Requirements
  PYTHON_REQUIREMENTS:  ${{ vars.PYTHON_REQUIREMENTS }}

  ## Terraform Application
  TERRAFORM_CLI:     ${{ vars.TERRAFORM_CLI }}
  TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}

  ## Update/Upgrade -> Python + PIP
  UPDATE_PIP:    ${{ vars.UPDATE_PIP }}
  UPDATE_PYTHON: ${{ vars.UPDATE_PYTHON }}

  ## Update/Upgrade -> System Components
  UPDATE_SYSTEM:  ${{ vars.UPDATE_SYSTEM }}
  UPGRADE_SYSTEM: ${{ vars.UPGRADE_SYSTEM }}

  ## Debugger & Verbosity Mode
  DEBUGER_MODE: ${{ vars.DEBUGER_MODE }}
  VERBOSE_MODE: ${{ vars.VERBOSE_MODE }}

####----------------------------------------------------------------------------

jobs:

  system-requirements:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v3

####----------------------------------------------------------------------------
## Session Timestamp

      - name: Session Timestamp
        id: session-timestamp
        shell: bash
        run: |

          SESSION_TIMESTAMP="$(date +"%y%m%d%H%M%S")" ;
          echo "SESSION_TIMESTAMP=${SESSION_TIMESTAMP}" >> ${GITHUB_ENV} ;

        continue-on-error: false

####----------------------------------------------------------------------------
## System Requirements

      - name: System Requirements
        uses: ./
        id: system-requirements
        with:

          debuger-mode: ${DEBUGGER_MODE}
          verbose-mode: ${VERBOSE_MODE}

          update-system:  ${UPDATE_SYSTEM}
          upgrade-system: ${UPGRADE_SYSTEM}

          update-python-version: ${UPDATE_PYTHON}
          update-pip-version:    ${UPDATE_PIP}

          install-default-tools: ${DEFAULT_TOOLS}
          install-custom-tools:  ${CUSTOM_TOOLS}

          install-python-requirements: ${PYTHON_REQUIREMENTS}

          install-awscli-cli:    ${AWSCLI_CLI}
          install-terraform-cli: ${TERRAFORM_CLI}

          terraform-version: ${TERRAFORM_VERSION}

        continue-on-error: false

####----------------------------------------------------------------------------
## Installed Packages

      - name: Installed Packages
        id: installed-packages
        shell: bash
        run: |

          lsb_release -a ;
          echo -e ;

          jq --version 2>/dev/null ;
          tree --version 2>/dev/null ;
          ncat --version 2>/dev/null ;
          echo -e ;

          python --version 2>/dev/null ;
          pip --version 2>/dev/null ;
          echo -e ;

          aws --version 2>/dev/null ;

          terraform --version >/dev/null 2>&1 && {
              echo -e "\nWhich package: $( which terraform )" ;
              # whereis terraform ;
              ls -al $(
                  dirname $( whereis terraform | cut -d' ' -f2 )
                )/terraform* 2>/dev/null ;
              echo -e ;
              echo -e "Listing current Terraform version:" ;
              ## TF_LOG=${terraform_loglevel} \
              terraform --version ;
              echo -e ;
            } ;

          echo -e ;

####----------------------------------------------------------------------------
